### ISSUE TITLE
feat: 사용자 정보 관련 기능 개발

### ISSUE THREAD

**Issue by xxoznge** [Food-GO/FoodGo-BE#12]
# Title

- 사용자 정보 관련 기능 개발

# TODO

- [ ] 사용자 아이디 중복 검사
- [ ] 사용자 닉네임 입력 및 중복 검사
- [ ] 회원 정보 입력

# etc

- nothing
