### ISSUE TITLE
feat: 커뮤니티 (친구 관리)

### ISSUE THREAD

**Issue by Jeongh00** [Food-GO/FoodGo-BE#18]
# Title

- 커뮤니티 친구 관리 기능

# TODO

- [x] 친구 신청 기능
- [x] 친구 리스트 조회
- [x] 친구 삭제
- [x] 친구 요청 현황 리스트

# etc

- 공통 파일 규격 정리
